### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lloricode** [elias123tre/bitwarden_find_duplicates#1] opened 2021-04-19 01:02 UTC
return blank and

![Screenshot from 2021-04-19 09-01-49](https://user-images.githubusercontent.com/8251344/115168543-ea16fb00-a0ed-11eb-91c3-4610bc388fea.png)

**Comment by lloricode** [comment] 2021-04-19 01:09
also when i run ` python bitwarden.py `, it returns this

![Screenshot from 2021-04-19 09-07-56](https://user-images.githubusercontent.com/8251344/115168840-d91ab980-a0ee-11eb-8536-7388c1a7dfe7.png)

**Comment by elias123tre** [comment] 2021-04-19 10:38
Your issue seems to be with using an older python version. I made the program in python 3.9 but have now backported it to at least 3.7 (havent tested earlier versions). That should fix the second error. Regarding the first error, the script seems to have trouble writing to the file `logins.js` which is required in rendering the duplicate logins, make sure you have write access to the directory and try again with the changes i have [commited](https://github.com/elias123tre/bitwarden_find_duplicates/commit/88742a34d30c83e56c8666944808a608d76076ce).

**Comment by lloricode** [comment] 2021-04-19 23:34
the previous error i was running `Python 2.7.18`,
also now i try it by `Python 3.8.5` by running command `python3 bitwarden.py`, it will return

```
Traceback (most recent call last):
  File "bitwarden.py", line 8, in <module>
    from tkinter import Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by lloricode** [comment] 2021-04-19 23:35
actually I'm not a python developer, so I can not understands what the problem

**Comment by lloricode** [comment] 2021-04-19 23:41
I try to install `python3.9.4`, then after running this command `python3.9 bitwarden.py`, this will return:

```
Traceback (most recent call last):
  File "/xxxxxxxxxxxxxx/bitwarden_find_duplicates/bitwarden.py", line 8, in <module>
    from tkinter import Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by elias123tre** [comment] 2021-04-20 09:59
Simply run `pip install tkinter` in the terminal to fix it. The problem is with your python installation. Tkinter is not included when using python as embeddable zip. You need to run full system installer and select install on `tcl/tk and IDLE`. Or just install it with pip.

**Comment by elias123tre** [comment] 2021-04-20 09:59
I may add a feature to specify file path of bitwarden export instad of using tkinter to select a file.

**Comment by lloricode** [comment] 2021-04-20 14:44
> I may add a feature to specify file path of bitwarden export instad of using tkinter to select a file.

will wait for this

thanks

**Comment by elias123tre** [comment] 2021-04-23 13:11
Closing this issue as the latest commit enables passing a filename as a parameter instead of choosing it with tkinter.
Open a new issue if you encounter any other problem.
[Commit with changes](https://github.com/elias123tre/bitwarden_find_duplicates/commit/ed76f4937b51e5407742095837d99a782b3c6a8d)

**Closed by elias123tre** 2021-04-23 13:11 UTC

**Comment by lloricode** [comment] 2021-04-23 13:35
it works thank you
